### PR TITLE
Added files required for starting node

### PR DESCRIPTION
**Pull request by ayushmishra2005**

### CODE REVIEW

**Comment by ayushmishra2005** [comment]
I will raise new PR.

**Comment by ltfschoen** [comment]
are we going to run collators with the telemetry flag? i.e. https://substrate.stackexchange.com/questions/818/telemetry-for-local-network

**Comment by ayushmishra2005** [comment]
> are we going to run collators with the telemetry flag? i.e. https://substrate.stackexchange.com/questions/818/telemetry-for-local-network

No. Do you want me to run with the telemetry flag?

**Comment by ltfschoen** [comment]
check with @cgroeschel first whether there are any risks. go through this guide https://docs.astar.network/maintain/collator/secure-validator, it suggests that collators only need p2p ports open

**Pull request closed without merging**
