### PR TITLE
Updated ParaId and Rococo Json

### PR DESCRIPTION
**Pull request by ayushmishra2005**
Since Rococo was restarted and our ParaId was allocated to some other chain, so as a part of this PR

1. We registered new paraid and replaced with existing one.
2. We pointed to latest `rococo.json` as suggested by community here https://matrix.to/#/!xVhtrCsUqgnxpwmsZq:matrix.parity.io/$TeagUwHxOWY4fcGy_KbZ3-Nss2NrvE6poCDZsILiy5k?via=matrix.parity.io&via=matrix.org
3. Added our chain's raw json, WASM, Genesis and compact wasm in `res` folder
4. Updated DataHighway release to `v3.3.0`

### CODE REVIEW

**Comment by ltfschoen** [comment]
could you please generate the files using the scripts in the scripts folder?

**Review by ltfschoen — CHANGES_REQUESTED** [review]
could you please generate the files using the script in the scripts folder (i.e. run `./scripts/dump_wasm_state_and_spec.sh "rococo"`)? and then rename and copy the generated files in the ./res folder so the filename also includes the parachain id.
if you want to name them like `para-2007--wasm` and `para-2007--genesis`, could you use a single dash (i.e. `para-2007-wasm` and `para-2007-genesis`) by doing `git mv para-2007--wasm para-2007-wasm && git mv para-2007--genesis para-2007-genesis`, and it would be preferable to have the chain name in those files (i.e. `rococo-parachain-2007-genesis` instead of just `rococo-parachain-2007-wasm` since later we'll also have those files for other relay chains like kusama). 
i can't see the point in storing them in a folder with the release version or adding the release version to the filename as users can just check the history of changes to the file in older commits, so we'll just use the same filename in new commits as we do chain upgrades as they'll correspond to new releases.
although for some reason when i generate the files with `./scripts/dump_wasm_state_and_spec.sh "rococo"`, the in the rococo.json file and rococo-raw-unsorted.json it still has `"para_id": 2026,` instead of `"para_id": 2007,` (i'm not sure why, because i did a global search in the directory for the text "2026" and i can't find any..

**Comment by ltfschoen** [comment]
@ayushmishra2005 could we please also include the x_runtime.compact.**compressed**.wasm file in the ./res/ folder (for both genesis and on-chain upgrades). see reason why here: https://substrate.stackexchange.com/a/845/83

**Review by cgroeschel — DISMISSED** [review]

**Comment by ltfschoen** [comment]
> although for some reason when i generate the files with `./scripts/dump_wasm_state_and_spec.sh "rococo"`, the in the rococo.json file and rococo-raw-unsorted.json it still has `"para_id": 2026,` instead of `"para_id": 2007,` (i'm not sure why, because i did a global search in the directory for the text "2026" and i can't find any..

i had to delete and generate the Cargo.lock file again to fix this. i also deleted the ./target/release folder before running `cargo build --release` to generate the new Cargo.lock, and then when i ran the script it generated the chain spec and "raw" chain definition files correctly with the correct parachain id inside

**Review by ltfschoen — DISMISSED** [review]

**Review by cgroeschel — APPROVED** [review]

**Review by ltfschoen — APPROVED** [review]

**Pull request merged**
