### PR TITLE
feat: Restore Substrate pallets for on-chain upgrade that were temporarily removed to minimise genesis runtime size for Rococo launch

### PR DESCRIPTION
**Pull request by ltfschoen**
* [X] Restore Substrate pallets that were removed to minimize runtime size for Rococo genesis launch. As part of launching on the Rococo parachain production testnet in this previous PR that was merged https://github.com/DataHighway-DHX/DataHighway-Parachain/pull/17, a recommendation was to minimise the runtime size and then perform incremental runtime upgrades to reintroduce the funcitonality.
Previously in that PR we removed the following Substrate pallets in the following commits: https://github.com/DataHighway-DHX/DataHighway-Parachain/pull/17/commits/e6edf898614f65f64e97f51a87e8a892c1de1605, https://github.com/DataHighway-DHX/DataHighway-Parachain/pull/17/commits/7a0810d7bde3e27dd8e5df880caf73ca11a52c7b, https://github.com/DataHighway-DHX/DataHighway-Parachain/pull/17/commits/676e96bdfcf5f27f89ea45d3586f009ed28aaa1f
These pallets have been restored in this PR using git revert.
* [X] Update versions in Cargo.toml files for and other parameters like `spec_version` and `impl_version` 
* [X] check that all essential pallet functionality works using polkadot.js
  * [X] balances - make transfers between accounts, hard spooned balances transferred from standalone to parachain
  * [X] democracy - create a preimage to transfer funds and use that preimage hash to create a proposal
  * [X] treasury - check 30 million DHX balance hard spooned from standalone to parachain
  * [X] sudo - check that sudo works for forceTransfer and setBalance
  * [X] staking - check that able to add additional collator nodes and they generate and finalize blocks
  * [X] runtime upgrade - check that able to perform a runtime upgrade by changing the existential deposit constant and using .compact.compressed.wasm file that is generated
  * [X] metadata - check that no errors in polkadot.js using custom_types.json
* [X] Linting to fix indentation issues
  * Unable to run benchmarks with `cargo build --release --features runtime-benchmarks`, as it gives the following erorr even though we're not evening using frame society, and even though `successful_origin` is already implemented in that branch here https://github.com/paritytech/substrate/blob/22d40c7/frame/society/src/lib.rs#L1278
* [X] - check that unit and integration tests still pass
* [ ] SKIPPED - Memory Profiling. See notes in https://github.com/DataHighway-DHX/DataHighway-Parachain/pull/17
* [ ] SKIPPED - Try-runtime. See notes in https://github.com/DataHighway-DHX/DataHighway-Parachain/pull/17
* [ ] SKIPPED - Benchmarking. See notes in https://github.com/DataHighway-DHX/DataHighway-Parachain/pull/17

* [X] Updates to incorporate changes from Substrate branch 'polkadot-v0.9.17' to 'polkadot-v0.9.18' that affected those pallets
* [X] Fix benchmarking script
* [X] Increment `spec_version` to `3`
* [X] Increment version of runtime and node from 3.4.0 to 3.5.0
* [X] Performed the following on the Rococo server (not local machine)
  * [X] Generated "raw" chain spec, wasm, and state files using ./scripts/dump_wasm_and_state_for_all_chains.sh and copied into both ./res folder and ./upgrades/3.5.0.   Important note: we need this changes to be deployed at genesis because it includes the Sudo pallet, which we need for on-chain runtime upgrades (we likely won't use the files in  ./upgrades/3.0.4 and ./upgrades/3.5.0)
  * [X] Build release and copy ./target/release/wbuild/datahighway-parachain-runtime.compact.wasm and .compact.compressed.wasm and store in /res folder for the latest changes in this PR for the parachains
* [ ] Generate new Github release (use contents of this checklist to mention what was done) and perform runtime upgrade on Rococo. Add DRAFT RELEASE MESSAGE below

```
v3.5.0

## What's Changed

* Restore pallets to the parachain again that were pruned from initial genesis Rococo deployment as recommmended by the Cumulus tutorial to minimize runtime size
* Updates to incorporate changes from Substrate branch 'polkadot-v0.9.17' to 'polkadot-v0.9.18' that affected those pallets
* Fixed logic in benchmarking script
* Check that all essential pallet functionality works using polkadot.js
  * Balances pallet - make transfers between accounts, hard spooned balances transferred from standalone to parachain
  * Democracy - create a preimage to transfer funds and use that preimage hash to create a proposal
  * Treasury - check 30 million DHX balance hard spooned from standalone to parachain
  * Sudo - check that sudo works for forceTransfer and setBalance
  * Collators - check that able to add additional collator nodes and they generate and finalize blocks
  * Runtime upgrade - check that able to perform a runtime upgrade by for example changing the existential deposit constant and using .compact.compressed.wasm file that is generated
  * Metadata - check that no browser errors in polkadot.js using custom_types.json
* Increment `spec_version` to `3` for use with on-chain runtime upgrade
* Increment version of runtime and node from 3.4.0 to 3.5.0
* check that unit and integration tests still pass
* Release build performed with the latest changes on the Rococo server and generated the plain and raw chain specification, wasm, and state files using ./scripts/dump_wasm_and_state_for_all_chains.sh and copied those files into the ./res folder. Copied the following files into the ./res folder after release build:
  * ./target/release/wbuild/datahighway-parachain-runtime/datahighway_parachain_runtime.compact.wasm
  * ./target/release/wbuild/datahighway-parachain-runtime/datahighway_parachain_runtime.compact.compressed.wasm
* Generate new Github release
```

### CODE REVIEW

**Review by cgroeschel — DISMISSED** [review]

**Review by ayushmishra2005 — CHANGES_REQUESTED** [review]
@ltfschoen Where did you generate `res/rococo-parachain-raw.json` file? On server or on local?

**Comment by ltfschoen** [comment]
> @ltfschoen Where did you generate `res/rococo-parachain-raw.json` file? On server or on local?

good point, yes we should generate that on the server and put a copy of it here

**Comment by ayushmishra2005** [comment]
> > @ltfschoen Where did you generate `res/rococo-parachain-raw.json` file? On server or on local?
> 
> good point, yes we should generate that on the server and put a copy of it here

Yes, Please generate fresh files on `Spreehafen`

**Comment by ltfschoen** [comment]
> > > @ltfschoen Where did you generate `res/rococo-parachain-raw.json` file? On server or on local?
> > 
> > 
> > good point, yes we should generate that on the server and put a copy of it here
> 
> Yes, Please generate fresh files on `Spreehafen`

i've made a commit that now includes the files that were generated on Spreehafen

**Review by ayushmishra2005 — APPROVED** [review]

**Pull request merged**
